### ISSUE TITLE
Error while closing repository

### ISSUE THREAD

**Issue by carlosedp** [ckipp01/mill-ci-release#21]
Using the plugin on my repo at <https://github.com/carlosedp/riscvassembler>, I'm getting the error:

```
Published riscvassembler_2.12, riscvassembler_2.13, riscvassembler_3, riscvassembler_native0.4_2.12, riscvassembler_native0.4_2.13, riscvassembler_native0.4_3 to Sonatype
Closing staging repository
Waiting for staging repository to close
Promoting staging repository
Waiting for staging repository to release
1 targets failed
io.kipp.mill.ci.release.ReleaseModule.publishAll java.util.NoSuchElementException: key not found: type
    scala.collection.MapOps.default(Map.scala:274)
    scala.collection.MapOps.default$(Map.scala:273)
    scala.collection.AbstractMap.default(Map.scala:405)
    scala.collection.MapOps.apply(Map.scala:176)
    scala.collection.MapOps.apply$(Map.scala:175)
    scala.collection.AbstractMap.apply(Map.scala:405)
    ujson.Value$Selector$StringSelector.apply(Value.scala:141)
    ujson.Value.apply(Value.scala:101)
    ujson.Value.apply$(Value.scala:101)
    ujson.Obj.apply(Value.scala:234)
    mill.scalalib.publish.SonatypeHttpApi.getStagingRepoState(SonatypeHttpApi.scala:68)
    mill.scalalib.publish.SonatypePublisher.isRightStatus$1(SonatypePublisher.scala:157)
    mill.scalalib.publish.SonatypePublisher.awaitRepoStatus(SonatypePublisher.scala:161)
    mill.scalalib.publish.SonatypePublisher.publishRelease(SonatypePublisher.scala:130)
    mill.scalalib.publish.SonatypePublisher.$anonfun$publishAll$11(SonatypePublisher.scala:72)
    mill.scalalib.publish.SonatypePublisher.$anonfun$publishAll$11$adapted(SonatypePublisher.scala:65)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    scala.collection.AbstractIterable.foreach(Iterable.scala:926)
    scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
    mill.scalalib.publish.SonatypePublisher.publishAll(SonatypePublisher.scala:65)
    io.kipp.mill.ci.release.ReleaseModule$.$anonfun$publishAll$2(CiReleaseModule.scala:112)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

The lib is published tho.

The error can be seen in the action here: https://github.com/carlosedp/riscvassembler/actions/runs/3045455104/jobs/4907137455

**Comment by carlosedp** [comment]
I've removed that section but still get the same error:

https://github.com/carlosedp/riscvassembler/actions/runs/3046733982/jobs/4909989073

Strange that publishing a snapshot (either on GitHub or locally) works fine:

https://github.com/carlosedp/riscvassembler/actions/runs/3046732400/jobs/4909981599

Ideas?

**Comment by ckipp01** [comment]
> I've removed that section but still get the same error:

yea, that shouldn't have anything to do with the error, it's just something I noticed.

> 
I've removed that section but still get the same error:

https://github.com/carlosedp/riscvassembler/actions/runs/3046733982/jobs/4909989073

Strange that publishing a snapshot (either on GitHub or locally) works fine:

https://github.com/carlosedp/riscvassembler/actions/runs/3046732400/jobs/4909981599

> Ideas?

Honestly, not really. If you tag a new tag, does it happen again? It'd be helpful to know if this is something that is continually happening or just a one off.

**Comment by carlosedp** [comment]
Happened to the last 2 times I've tagged a release.

**Comment by carlosedp** [comment]
Weirdly enough recent versions were published successfully with no changes to config.
https://github.com/carlosedp/riscvassembler/actions/runs/3137665933/jobs/5096200306

Thanks and sorry about the hassle!

**Comment by ckipp01** [comment]
> Thanks and sorry about the hassle!

No worries! Glad it's working!

**Comment by carlosedp** [comment]
Started getting the same error again on my repo...

https://github.com/carlosedp/zio-channel/actions/runs/5577752821/jobs/10193391142

I re-created the secrets for SONATYPE and PGP but same keeps happening.

Any idea? :)

**Comment by carlosedp** [comment]
Dunno why, failed twice then worked... 🤷🏻‍♂️
Again, sorry about the noise.
